# Port number
server:
  port: 9090


# Database configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root   # Local database username
    password: 0817 # Local database password
    url: jdbc:mysql://localhost:3306/mysystem?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springboot.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl